kumuluzee:
  name: catalog
  version: 1.0.0
  env:
    name: dev
  server:
    #base-url: http://prpo-priporocilni-sistem-prpo-priporocilni-sistem.apps.us-west-1.starter.openshift-online.com/v1/priporocila
    http:
      port: 5555
  datasources:
    - jndi-name: jdbc/ItemDS
##      connection-url: jdbc:postgresql://database:5432/rentarich
#      connection-url: jdbc:postgresql://localhost:5432/rentarich
#      username: postgres
#      password: postgres
      connection-url: jdbc:postgresql://fanny.db.elephantsql.com:5432/sewztpca
      username: sewztpca
      password: jviqrny5vLJYogFEeyBhAr7daifOAiwB
      max-pool-size: 1
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/ItemDS
      disk-space-health-check:
        threshold: 10
      http-health-check:
        connection-url: http://20.88.160.36
  metrics:
    servlet:
      enabled: true
      mapping: /metrics
  graphql:
    schema:
      include-scalars: true
      include-schema-definition: true
      include-directives: true
      include-introspection-types: true
  openapi:
    ui:
      enabled: true
#  config:
#    consul:
#      agent: http://20.88.160.36
#  discovery:
#    consul:
#      agent: http://20.88.160.36


rest-properties:
  maintenance: false
  url: 20.62.179.11