kumuluzee:
  name: recommendation-system
  version: 1.0.0
  env:
    name: dev
  server:
    base-url: http://localhost:/
    #base-url: http://prpo-priporocilni-sistem-prpo-priporocilni-sistem.apps.us-west-1.starter.openshift-online.com/v1/priporocila
    http:
      port: 5555
  datasources:
    - jndi-name: jdbc/ItemDS
##      connection-url: jdbc:postgresql://database:5432/rentarich
#      connection-url: jdbc:postgresql://localhost:5432/rentarich
#      username: postgres
#      password: postgres
      connection-url: jdbc:postgresql://fanny.db.elephantsql.com:5432/wuztpoqp
      username: wuztpoqp
      password: 50Xsd8IBKM6kyELj0WzemRZlOXyHCulg
      max-pool-size: 2
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/ItemDS
  metrics:
    servlet:
      enabled: true
      mapping: /metrics

rest-properties:
  maintenance: false