kumuluzee:
  name: catalog
  version: 1.0.0
  env:
    name: dev
  server:
    #base-url: http://prpo-priporocilni-sistem-prpo-priporocilni-sistem.apps.us-west-1.starter.openshift-online.com/v1/priporocila
    http:
      port: 5555
  datasources:
    - jndi-name: jdbc/ItemDS
##      connection-url: jdbc:postgresql://database:5432/rentarich
#      connection-url: jdbc:postgresql://localhost:5432/rentarich
#      username: postgres
#      password: postgres
      connection-url: jdbc:postgresql://fanny.db.elephantsql.com:5432/sewztpca
      username: sewztpca
      password: jviqrny5vLJYogFEeyBhAr7daifOAiwB
      max-pool-size: 1
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/ItemDS
      disk-space-health-check:
        threshold: 10
#      http-health-check:
#        connection-url: http://google.com
  metrics:
    servlet:
      enabled: true
      mapping: /metrics
  graphql:
    schema:
      include-scalars: true
      include-schema-definition: true
      include-directives: true
      include-introspection-types: true
  openapi:
    ui:
      enabled: true
  cors-filter:
    servlet:
      allow-generic-http-requests: true
      allow-origin: "*"

  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                             <Configuration name="comments">
                                 <Appenders>
                                     <Console name="console" target="SYSTEM_OUT">
                                         <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                     </Console>
                                     <Socket name="logstash" host="c9bdc69b-e1c8-45b8-843c-bd811a1d5835-ls.logit.io"
                                     port="18974" protocol="udp">
                                         <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                                     </Socket>
                                 </Appenders>
                                 <Loggers>
                                     <!-- Default logger -->
                                     <Root level="all">
                                         <AppenderRef ref="console" level="info" />
                                         <AppenderRef ref="logstash" level="info" />
                                     </Root>
                                 </Loggers>
                             </Configuration>'

#  config:
#    consul:
#      agent: http://20.88.160.36
#  discovery:
#    consul:
#      agent: http://20.88.160.36


rest-properties:
  maintenance: false
  url: 20.62.179.11