INSERT INTO items (title, description, category) VALUES ('Basketball ball','Ball for playing basketball.','Sports');
INSERT INTO items (title, description, category) VALUES ('Poker cards','Cards for playing poker.','Board game');
INSERT INTO items (title, description, category) VALUES ('Remi cards','Cards for remi.','Board game');
INSERT INTO items (title, description, category) VALUES ('Remi cards','Cards for remi.','Board game');
INSERT INTO items (title, description, category) VALUES ('Remi cards','Cards for remi.','Board game');
INSERT INTO items (title, description, category) VALUES ('Remi cards','Cards for remi.','Board game');
INSERT INTO items (title, description, category) VALUES ('Remi cards','Cards for remi.','Board game');
INSERT INTO items (title, description, category) VALUES ('Remi cards','Cards for remi.','Board game');
INSERT INTO items (title, description, category) VALUES ('Remi cards','Cards for remi.','Board game');
INSERT INTO items (title, description, category) VALUES ('Remi cards','Cards for remi.','Board game');
